### ISSUE TITLE
Build without AppStore Developer Account

### ISSUE THREAD

**Issue by snunez1** [graphsketcher/GraphSketcher#19]
Does anyone have the formula for building this without an Apple developer signing key? It doesn't make sense to pay $100 just to try it out, especially if you're never going to build it for the app store.

**Comment by dnivi3** [comment]
There is a ready-made build right here: https://github.com/graphsketcher/GraphSketcher/releases

**Comment by snunez1** [comment]
That's the one I'm using thanks, but as a binary I can't make changes to it. I need modify the source.

**Comment by correia** [comment]
You don't need a paid Apple Developer account, or a Developer ID certificate to build GraphSketcher.

However, since GraphSketcher is sandboxed, it **must** be code-signed.

The easiest way to do this is to generate a self-signed certificate that matches the pattern the build system is already looking for: "Mac Developer: Your Name".

For more information, see:

```
https://developer.apple.com/library/mac/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html
```
